inherit_from: .rubocop_todo.yml

require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
